version: "3.9"

services:
  elastic-catalog:
    image: elasticsearch:8.6.1
    container_name: elastic-catalog
    restart: always
    network_mode: bridge
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: "elastic"